algoritmo "DiaSemana"
var
      dia:inteiro
inicio
      escreva("qual o dia da semana ? ")
         leia(dia)
         
      escolha(dia)
             caso 1
                 escreva("ESTE DIA SE REFERE A SEGUNDA-FEIRA")
             caso 2
                 escreva("ESTE DIA SE REFERE A TERÇA-FEIRA")
             caso 3
                 escreva("ESTE DIA SE REFERE A QUARTA-FEIRA")
             caso 4
                 escreva("ESTE DIA SE REFERE A QUINTA-FEIRA")
             caso 5
                 escreva("ESTE DIA SE REFERE A SEXTA-FEIRA")
             caso 6
                 escreva("ESTE DIA SE REFERE A SÁBADO")
             caso 7
                 escreva("ESTE DIA SE REFERE A DOMINGO")
      fimescolha
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
fimalgoritmo