algoritmo "piramide"
var
    cont1,cont2,cont3,cont4,cont5,cont6,cont7,cont8,cont9,cont10:inteiro
inicio
      para cont1 de 1 ate 1 passo 1 faca
          escreva(cont1)
      fimpara
      escreval(" ")
      para cont2 de 1 ate 2 passo 1 faca
          escreva(cont2)
      fimpara
      escreval(" ")
      para cont3 de 1 ate 3 passo 1 faca
          escreva(cont3)
      fimpara
      escreval(" ")
      para cont4 de 1 ate 4 passo 1 faca
          escreva(cont4)
      fimpara
      escreval(" ")
      para cont5 de 1 ate 5 passo 1 faca
          escreva(cont5)
      fimpara
      escreval(" ")
      para cont6 de 1 ate 6 passo 1 faca
          escreva(cont6)
      fimpara
      escreval(" ")
      para cont7 de 1 ate 7 passo 1 faca
          escreva(cont7)
      fimpara
      escreval(" ")
      para cont8 de 1 ate 8 passo 1 faca
          escreva(cont8)
      fimpara
      escreval(" ")
      para cont9 de 1 ate 9 passo 1 faca
          escreva(cont9)
      fimpara
      escreval(" ")
      para cont10 de 1 ate 10 passo 1 faca
          escreva(cont10)
      fimpara
      
      
      
      
      
      
      
      
      
      
fimalgoritmo