algoritmo "quadrado"
var
    calc1,calc2,calc3,calc4,calc5,soma:real
inicio
       calc1 <- 1^2
       calc2 <- 2^2
       calc3 <- 3^2
       calc4 <- 4^2
       calc5 <- 5^2
       soma <- calc1+calc2+calc3+calc4+calc5
       
       escreval("1 ao quadrado = ",calc1)
       escreval("2 ao quadrado = ",calc2)
       escreval("3 ao quadrado = ",calc3)
       escreval("4 ao quadrado = ",calc4)
       escreval("5 ao quadrado = ",calc5)
       escreval("- A soma dos quadrados é de : ",soma)
fimalgoritmo